### ISSUE TITLE
What's the correct way to work with forms?

### ISSUE THREAD

**Issue by 4orever** [Rovak/KJSencha#24]
There are to ways to work with forms using KJSencha:
1. Set 'api.submit' config option and then do form.submit() and @Formhandler annotation. So the main question:
   What is the correct way to get form POST data?
2. Use getForm().getRecord() and then call create/update direct method.

Is there any advantages of first variant?

**Comment by Rovak** [comment]
The correct way is to use the form submit method with the @Formhandler annotation and then retrieve the POST values from the first function parameter. 

An example can be found here: [PHP](https://github.com/KablauJoustra/KJSenchaExample/blob/master/module/Application/src/Application/Direct/NamedArguments.php#L16), [JS](https://github.com/KablauJoustra/KJSenchaExample/blob/master/public/js/app/view/direct/Named.js#L50)

The example works but is a bit misleading, the handler may not be necessary for your situation. You can still specify the methods by configuring the api methods as shown [here](https://github.com/KablauJoustra/KJSenchaExample/blob/master/public/js/app/view/direct/Form.js#L20), and use the values as demonstrated in the previous example.

**Comment by 4orever** [comment]
Rovak, thank you for your answer!
It's logical, I should guess.
