### ISSUE TITLE
KJSenchaExample

### ISSUE THREAD

**Issue by mgrom** [Rovak/KJSencha#37]
Hi,

Could you please update https://github.com/Rovak/KJSenchaExample ? I think that is not working correctly. Correct me if I'm wrong coz I'm new in Zend 2 and ExtJS.

Thanks in an advance.

**Comment by Rovak** [comment]
I've just tried the following in a Ubuntu environment with PHP 5.5.3:

``` sh
git clone git@github.com:Rovak/KJSenchaExample.git
cd KJSenchaExample
php composer.phar self-update
php composer.phar install
```

And then navigate with a browser to the public folder which shows the application working properly.

Could you specify the errors that you are encountering when opening the application, and which environment + browser you are using?

**Comment by mgrom** [comment]
About environment:
Win7
PHP Version 5.4.21
Zend Server Version: 6.2.0
Zend Framework: 2.2.5

Error:
![image](https://f.cloud.github.com/assets/1607362/1889776/1dcf2026-7a22-11e3-89d5-5c5619ba33b7.png)

Let's say I've managed somehow this... but I'm not sure that it should be done this way.
What have I done? I've moved all JS files from /module/Application/public to /public/

So... any idea why this is not working from the begining ?

**Comment by Rovak** [comment]
Are you sure that you are opening the appliction in the /public/ folder? Looking at the urls i think that the htaccess is not working properly or that you moved the index.php to the root of the project

**Comment by mgrom** [comment]
Yes, I'm sure. After removing index file from the folder effect was visible
through browser.
10 sty 2014 22:04 "Roy van Kaathoven" notifications@github.com napisał(a):

**Comment by Rovak** [comment]
I made a private repo for which i send you an invite, could you upload a snapshot of the directory to the repository so i can take a look at it?
