### ISSUE TITLE
ExtJs Version

### ISSUE THREAD

**Issue by Amri94** [Rovak/KJSencha#39]
How can I update the version of Sencha ExtJs used in this module?

**Comment by Rovak** [comment]
The library can be updated by changing the `library_path` settings [here](https://github.com/Rovak/KJSencha/blob/master/config/module.config.php#L12) to a newer version

**Comment by Rovak** [comment]
Added to [docs](http://kjsencha.readthedocs.org/topics/configuration.html)

**Comment by Amri94** [comment]
Thank you
